# Generated by Django 5.0.3 on 2024-03-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addbookmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('year', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('al', 'Algorithms'), ('ai', 'Artificial Intelligence'), ('ml', 'Machine Learning'), ('pro', 'Programming'), ('net', 'Networking'), ('hr', 'Hardware')], max_length=3)),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='adminsignupmodel',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
