# Generated by Django 5.0.3 on 2024-03-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_addbookmodel_shelf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbookmodel',
            name='shelf',
        ),
    ]
