# Generated by Django 5.0.3 on 2024-03-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_newbookmodel_delete_addbookmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbookmodel',
            name='shelf',
            field=models.FloatField(default=None),
        ),
    ]
