# Generated by Django 5.0.3 on 2024-03-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_newbookmodel_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbookmodel',
            name='shelf',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
