# Generated by Django 5.0.3 on 2024-03-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_remove_newbookmodel_shelf_newbookmodel_shelfid'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentsignupmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('M.Tech', 'Image Processing')], max_length=6)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
            ],
        ),
    ]
