# Generated by Django 4.2.5 on 2024-03-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_issuedbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='bookname',
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='lastname',
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.newbookmodel'),
        ),
    ]
