# Generated by Django 4.2.5 on 2024-03-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_alter_issuedbook_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='book',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
