# Generated by Django 4.2.5 on 2024-03-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_alter_issuedbook_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='book',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
