# Generated by Django 4.2.5 on 2024-03-17 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newapp', '0019_alter_issuedbook_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbook',
            name='book',
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.newbookmodel'),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
