# Generated by Django 4.2.5 on 2024-03-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_remove_issuedbook_book_issuedbook_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbook',
            name='user_id',
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='book',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='student',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
